bootstrap.servers=localhost:9092,localhost:9093,localhost:9094
topic.name=customer-purchases

producer.key.serializer=org.apache.kafka.common.serialization.StringSerializer
producer.value.serializer=io.confluent.kafka.serializers.KafkaAvroSerializer

consumer.group.id=rewards-group

consumer.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
consumer.value.deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer

consumer.auto.offset.reset=earliest

schema.registry.url=http://localhost:8081
specific.avro.reader=true