bootstrap.servers=localhost:9092,localhost:9093,localhost:9094

topic.name=transactions

client.id=payment-service-v5

message.count=10000

acks=1

linger.ms=100

batch.size=16384

compression.type=snappy